spring.datasource:
  url: jdbc:postgresql://localhost:5432/docdrop
  username: postgres
  password: postgres

spring.mvc:
  static-path-pattern: /static/**

upload:
  path: "./upload"

storage:
  path: "./upload"

spring:
  jpa:
    show-sql: true
  batch:
    # Don't start jobs on boot, when jobs are run is determined by the application
    job.enabled: false


#logging:
#  level:
#    org.springframework.transaction: TRACE